services:
  glinet-fw-monitor:
    image: ghcr.io/wickedyoda/docker-monitor-fw.gl-inet.com:latest
    container_name: glinet-fw-monitor
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped