services:
  glinet-fw-monitor:
    build: .
    container_name: glinet-fw-monitor
    environment:
      WEBSITE: https://fw.gl-inet.com
      DISCORD_WEBHOOK: https://discord.com/api/webhooks/REPLACE_ME
      DRY_RUN: "true"

      DISCORD_TITLE: "GL.iNet Firmware Monitor (Test)"
      DISCORD_PREFIX: "Firmware change detected:"
      DISCORD_SUFFIX: "Check compatibility before upgrading."
      DISCORD_EMOJI: "ðŸ“¦"

    volumes:
      - ./data:/data
    restart: unless-stopped
